// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetSecKillInfoReply struct {
	Code    int64                   `json:"code"`
	Message string                  `json:"message"`
	Data    GetSecKillInfoReplyData `json:"data"`
}

type GetSecKillInfoReplyData struct {
	Status   int64  `json:"status"`
	OrderNum string `json:"orderNum"`
	SecNum   string `json:"secNum"`
	GoodsNum string `json:"goodsNum"`
}

type GetSecKillInfoRequest struct {
	SecNum string `form:"sec_num"`
}

type GetUserByNameRequest struct {
	UserName    string `form:"user_name,optional"`
	UserNameAlt string `form:"userName,optional"`
}

type GetUserReply struct {
	Code    int64    `json:"code"`
	Message string   `json:"message"`
	Data    UserData `json:"data"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code   int64  `json:"code"`
	Token  string `json:"token"`
	Expire string `json:"expire"`
}

type SecKillRequest struct {
	GoodsNum string `json:"goodsNum"`
	Num      int32  `json:"num"`
}

type SecKillV1Reply struct {
	Code    int64              `json:"code"`
	Message string             `json:"message"`
	Data    SecKillV1ReplyData `json:"data"`
}

type SecKillV1ReplyData struct {
	OrderNum string `json:"orderNum"`
}

type SecKillV2Reply struct {
	Code    int64              `json:"code"`
	Message string             `json:"message"`
	Data    SecKillV2ReplyData `json:"data"`
}

type SecKillV2ReplyData struct {
	OrderNum string `json:"orderNum"`
}

type SecKillV3Reply struct {
	Code    int64              `json:"code"`
	Message string             `json:"message"`
	Data    SecKillV3ReplyData `json:"data"`
}

type SecKillV3ReplyData struct {
	SecNum string `json:"secNum"`
}

type UserData struct {
	UserID   string `json:"userID"`
	UserName string `json:"userName"`
	Pwd      string `json:"pwd"`
	Sex      int64  `json:"sex"`
	Age      int64  `json:"age"`
	Email    string `json:"email"`
	Contact  string `json:"contact"`
	Mobile   string `json:"mobile"`
	IdCard   string `json:"idCard"`
}

type WelcomeResponse struct {
	Welcome string `json:"welcome"`
}
