/path/to/Microsecond\ killing\ service/gateway-main/logs/*.log
/path/to/Microsecond\ killing\ service/user-main/logs/*.log
/path/to/Microsecond\ killing\ service/seckill-main/logs/*.log {
    size 100M
    rotate 7
    maxage 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
