// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/BitofferHub/user/internal/logic/user"
	"github.com/BitofferHub/user/internal/svc"
	v1 "github.com/BitofferHub/user/api/user/v1"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) CreateUser(ctx context.Context, in *v1.CreateUserRequest) (*v1.CreateUserReply, error) {
	l := userlogic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServer) UpdateUser(ctx context.Context, in *v1.UpdateUserRequest) (*v1.UpdateUserReply, error) {
	l := userlogic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *UserServer) DeleteUser(ctx context.Context, in *v1.DeleteUserRequest) (*v1.DeleteUserReply, error) {
	l := userlogic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *v1.GetUserRequest) (*v1.GetUserReply, error) {
	l := userlogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) GetUserByName(ctx context.Context, in *v1.GetUserByNameRequest) (*v1.GetUserByNameReply, error) {
	l := userlogic.NewGetUserByNameLogic(ctx, s.svcCtx)
	return l.GetUserByName(in)
}

func (s *UserServer) ListUser(ctx context.Context, in *v1.ListUserRequest) (*v1.ListUserReply, error) {
	l := userlogic.NewListUserLogic(ctx, s.svcCtx)
	return l.ListUser(in)
}
